// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmB5_wKsgsKFdMphl4tUU0aibopzIiwLI',
    appId: '1:1078067383113:web:8a22408160a2614d376898',
    messagingSenderId: '1078067383113',
    projectId: 'fatem-app-4a429',
    authDomain: 'fatem-app-4a429.firebaseapp.com',
    storageBucket: 'fatem-app-4a429.appspot.com',
    measurementId: 'G-ZVMV79XXJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5yhwtK34QhD5NceT2eQ4iHnheRDtBli8',
    appId: '1:1078067383113:android:fe5a2323490686df376898',
    messagingSenderId: '1078067383113',
    projectId: 'fatem-app-4a429',
    storageBucket: 'fatem-app-4a429.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOowZAHqru97KXrNxFeYnc3TgoIuqevxs',
    appId: '1:1078067383113:ios:20c540209db4d7b3376898',
    messagingSenderId: '1078067383113',
    projectId: 'fatem-app-4a429',
    storageBucket: 'fatem-app-4a429.appspot.com',
    iosBundleId: 'com.fatemusers.fatemUsers',
  );
}
